package com.ilmagna.allworkadmin.api.config;

public class ApiErrorCode {
	//공통
	public static final int ECODE_FIRST = 10000;
	public static final int ECODE_INTERNAL_EXCEPTION = ECODE_FIRST + 1;
	public static final int ECODE_INVALID_FORM_DATA = ECODE_INTERNAL_EXCEPTION + 1;
	public static final int ECODE_LOGIN_REQUIRED = ECODE_INVALID_FORM_DATA + 1;
	public static final int ECODE_UNDER_CONSTRUCTION = ECODE_LOGIN_REQUIRED + 1;

	public static final int ECODE_LAST = ECODE_UNDER_CONSTRUCTION + 1;

	//Login/Logout
	public static final int ECODE_LOGIN_FIRST = ECODE_LAST + 100;
	public static final int ECODE_LOGIN_INVALID_ACCOUNT = ECODE_LOGIN_FIRST + 1;
	public static final int ECODE_LOGIN_ROLE_FAIL = ECODE_LOGIN_INVALID_ACCOUNT + 1;

	public static final int ECODE_LOGIN_LAST = ECODE_LOGIN_ROLE_FAIL + 1;

	//관리자 권한 관리.
	public static final int ECODE_ADMIN_ROLE_FIRST = ECODE_LOGIN_LAST + 100;
	public static final int ECODE_ADMIN_ROLE_FIND_FAIL = ECODE_ADMIN_ROLE_FIRST + 1;
	public static final int ECODE_ADMIN_ROLE_DUPLICATED = ECODE_ADMIN_ROLE_FIND_FAIL + 1;
	public static final int ECODE_ADMIN_ROLE_UPDATE_FIND_FAIL = ECODE_ADMIN_ROLE_DUPLICATED + 1;
	public static final int ECODE_ADMIN_ROLE_DELETE_FIND_FAIL = ECODE_ADMIN_ROLE_UPDATE_FIND_FAIL + 1;

	public static final int ECODE_ADMIN_ROLE_LAST = ECODE_ADMIN_ROLE_DELETE_FIND_FAIL + 1;
	
	//관리자  관리.
	public static final int ECODE_ADMIN_FIRST = ECODE_ADMIN_ROLE_LAST + 100;
	public static final int ECODE_ADMIN_FIND_FAIL = ECODE_ADMIN_FIRST + 1;
	public static final int ECODE_ADMIN_DUPLICATED = ECODE_ADMIN_FIND_FAIL + 1;
	public static final int ECODE_ADMIN_UPDATE_FIND_FAIL = ECODE_ADMIN_DUPLICATED + 1;
	public static final int ECODE_ADMIN_DELETE_FIND_FAIL = ECODE_ADMIN_UPDATE_FIND_FAIL + 1;

	public static final int ECODE_ADMIN_LAST = ECODE_ADMIN_DELETE_FIND_FAIL + 1;
	
	//사용자 유형 관리.
	public static final int ECODE_USER_ROLE_FIRST = ECODE_ADMIN_LAST + 100;
	public static final int ECODE_USER_ROLE_FIND_FAIL = ECODE_USER_ROLE_FIRST + 1;
	public static final int ECODE_USER_ROLE_DUPLICATED = ECODE_USER_ROLE_FIND_FAIL + 1;
	public static final int ECODE_USER_ROLE_UPDATE_FIND_FAIL = ECODE_USER_ROLE_DUPLICATED + 1;
	public static final int ECODE_USER_ROLE_DELETE_FIND_FAIL = ECODE_USER_ROLE_UPDATE_FIND_FAIL + 1;

	public static final int ECODE_USER_ROLE_LAST = ECODE_USER_ROLE_DELETE_FIND_FAIL + 1;

	//사용자  관리.
	public static final int ECODE_USER_FIRST = ECODE_USER_ROLE_LAST + 100;
	public static final int ECODE_USER_FIND_FAIL = ECODE_USER_FIRST + 1;
	public static final int ECODE_USER_DUPLICATED = ECODE_USER_FIND_FAIL + 1;
	public static final int ECODE_USER_UPDATE_FIND_FAIL = ECODE_USER_DUPLICATED + 1;
	public static final int ECODE_USER_DELETE_FIND_FAIL = ECODE_USER_UPDATE_FIND_FAIL + 1;

	public static final int ECODE_USER_LAST = ECODE_USER_DELETE_FIND_FAIL + 1;

	
	//판매 기록.
	public static final int ECODE_SALES_RECORD_FIRST = ECODE_USER_LAST + 100;
	public static final int ECODE_SALES_RECORD_FIND_FAIL = ECODE_SALES_RECORD_FIRST + 1;
	public static final int ECODE_SALES_RECORD_DUPLICATED = ECODE_SALES_RECORD_FIND_FAIL + 1;
	public static final int ECODE_SALES_RECORD_UPDATE_FIND_FAIL = ECODE_SALES_RECORD_DUPLICATED + 1;
	public static final int ECODE_SALES_RECORD_DELETE_FIND_FAIL = ECODE_SALES_RECORD_UPDATE_FIND_FAIL + 1;

	public static final int ECODE_SALES_RECORD_LAST = ECODE_SALES_RECORD_DELETE_FIND_FAIL + 1;
	
	//주유기 기록.
	public static final int ECODE_NOZZLE_RECORD_FIRST = ECODE_SALES_RECORD_LAST + 100;
	public static final int ECODE_NOZZLE_RECORD_FIND_FAIL = ECODE_NOZZLE_RECORD_FIRST + 1;
	public static final int ECODE_NOZZLE_RECORD_DUPLICATED = ECODE_NOZZLE_RECORD_FIND_FAIL + 1;
	public static final int ECODE_NOZZLE_RECORD_UPDATE_FIND_FAIL = ECODE_NOZZLE_RECORD_DUPLICATED + 1;
	public static final int ECODE_NOZZLE_RECORD_DELETE_FIND_FAIL = ECODE_NOZZLE_RECORD_UPDATE_FIND_FAIL + 1;

	public static final int ECODE_NOZZLE_RECORD_LAST = ECODE_NOZZLE_RECORD_DELETE_FIND_FAIL + 1;
	
	//주유탱크 액세스 기록.
	public static final int ECODE_TANK_RECORD_FIRST = ECODE_NOZZLE_RECORD_LAST + 100;
	public static final int ECODE_TANK_RECORD_FIND_FAIL = ECODE_TANK_RECORD_FIRST + 1;
	public static final int ECODE_TANK_RECORD_DUPLICATED = ECODE_TANK_RECORD_FIND_FAIL + 1;
	public static final int ECODE_TANK_RECORD_UPDATE_FIND_FAIL = ECODE_TANK_RECORD_DUPLICATED + 1;
	public static final int ECODE_TANK_RECORD_DELETE_FIND_FAIL = ECODE_TANK_RECORD_UPDATE_FIND_FAIL + 1;

	public static final int ECODE_TANK_RECORD_LAST = ECODE_TANK_RECORD_DELETE_FIND_FAIL + 1;

	//주유탱크 측정기록.
	public static final int ECODE_TANK_BALANCE_RECORD_FIRST = ECODE_TANK_RECORD_LAST + 100;
	public static final int ECODE_TANK_BALANCE_RECORD_FIND_FAIL = ECODE_TANK_BALANCE_RECORD_FIRST + 1;
	public static final int ECODE_TANK_BALANCE_RECORD_DUPLICATED = ECODE_TANK_BALANCE_RECORD_FIND_FAIL + 1;
	public static final int ECODE_TANK_BALANCE_RECORD_UPDATE_FIND_FAIL = ECODE_TANK_BALANCE_RECORD_DUPLICATED + 1;
	public static final int ECODE_TANK_BALANCE_RECORD_DELETE_FIND_FAIL = ECODE_TANK_BALANCE_RECORD_UPDATE_FIND_FAIL + 1;

	public static final int ECODE_TANK_BALANCE_RECORD_LAST = ECODE_TANK_BALANCE_RECORD_DELETE_FIND_FAIL + 1;
}
